### PR TITLE
Fixed link to travis ci build status

### PR DESCRIPTION
**Pull request by fatroom**
fix link to travis after moving the repo

### CODE REVIEW

**Comment by fatroom** [comment]
What message patterns do you have configured in zappr?

**Comment by mrandi** [comment]
👍

**Comment by mrandi** [comment]
@fatroom you need to change the organization visibility, here:
https://github.com/orgs/zalando-incubator/people?utf8=%E2%9C%93&query=fat
https://github.com/orgs/zalando/people?utf8=%E2%9C%93&query=fat

**Comment by fatroom** [comment]
Did that

**Comment by mrandi** [comment]
@fatroom the message is the default one 👍

**Comment by fatroom** [comment]
that's for commit approval, but i see that you also got commit message check enabled which is failed for this PR.

**Comment by fatroom** [comment]
👍

**Comment by mrandi** [comment]
@fatroom was done by mistake, I remove it now! thx

**Pull request merged**
